helmCharts:
- name: kyverno
  includeCRDs: true
  valuesInline:
    rbac:
      create: false
    metricsService:
      create: false
    serviceMonitor:
      enabled: false
    installCRDs: true
  releaseName: kyverno
  version: 2.5.1
  repo: https://kyverno.github.io/kyverno

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kyverno
  $patch: delete
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kyverno-metrics
  $patch: delete
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: kyverno-svc
  $patch: delete
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kyverno
  $patch: delete
- |-
  apiVersion: v1
  kind: Pod
  metadata:
    name: kyverno-test
  $patch: delete
