apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3002"
  name: kyverno
spec:
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: kyverno
                    operator: In
                    values:
                      - dev
                  - key: clusterId
                    operator: In
                    values:
                      - in-cluster-local
                  - key: clusterName
                    operator: In
                    values:
                      - c-build-1
              values:
                path: kyverno/1.8.0-rc1
                valueFile: values-in-cluster-local.yaml
          - clusters:
              selector:
                matchExpressions:
                  - key: kyverno
                    operator: Exists
                  - key: clusterId
                    operator: NotIn
                    values:
                      - in-cluster-local
              values:
                path: kyverno/1.7.1
                valueFile: values.yaml
  template:
    metadata:
      name: 'kyverno-{{name}}'
      labels:
        appset: kyverno
        clusterId: '{{metadata.labels.clusterId}}'
        environmentId: '{{metadata.labels.environmentId}}'
      annotations:
        argocd.argoproj.io/sync-wave: "3002"
        version: '{{values.path}}'
    spec:
      project: kyverno
      source:
        helm:
          valueFiles:
          - '{{values.valueFile}}'
        repoURL: 'https://github.com/ron1/ron1-kyverno-gitops.git'
        targetRevision: HEAD
        path: '{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: kyverno
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
