apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3001"
  name: kyverno-crd
spec:
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
# Placeholder dummy cluster
          - clusters:
              selector:
                matchExpressions:
                  - key: kyverno
                    operator: DoesNotExist
                  - key: kyverno
                    operator: Exists
                  - key: kyverno
                    operator: NotIn
                    values:
                      - dev
              values:
                path: kyverno-crd/1.7.1
          - clusters:
              selector:
                matchExpressions:
                  - key: kyverno
                    operator: Exists
                  - key: kyverno
                    operator: NotIn
                    values:
                      - dev
              values:
                path: kyverno-crd/1.7.1
  template:
    metadata:
      name: 'kyverno-crd-{{name}}'
      labels:
        appset: kyverno-crd
        clusterId: '{{metadata.labels.clusterId}}'
        environmentId: '{{metadata.labels.environmentId}}'
      annotations:
        argocd.argoproj.io/sync-wave: "3001"
        version: '{{values.path}}'
    spec:
      project: kyverno
      source:
        repoURL: 'https://github.com/ron1/ron1-kyverno-gitops.git'
        targetRevision: HEAD
        path: '{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: kyverno
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
