apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno-merge
spec:
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusters:
              selector:
                matchLabels:
                  clusterId: in-cluster-local
              values:
                path: kyverno/1.7.1
          - clusters:
              selector:
                matchLabels:
                  unspecified: unspecified
              values:
                path: kyverno/1.7.2
  template:
    metadata:
      name: 'kyverno-me-{{name}}'
      labels:
        appset: kyverno-merge
      annotations:
        version: '{{values.path}}'
    spec:
      project: kyverno
      source:
        helm:
          fileParameters:
            - path: values.yaml
        repoURL: 'https://github.com/ron1/ron1-kyverno-gitops.git'
        targetRevision: HEAD
        path: '{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: kyverno
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
