apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3001"
  name: kyverno-merge
spec:
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          # all clusters w/downstream valueFile
          - clusters:
              values:
                path: kyverno/1.7.1
                valueFile: values.yaml
          # in-cluster-local clusters w/mgmt valueFile
          - clusters:
              selector:
                matchExpressions:
                  - key: clusterId
                    operator: In
                    values:
                      - in-cluster-local
              values:
                path: kyverno/1.8.0-rc1
                valueFile: values-in-cluster-local.yaml
          # kyverno: dev labeled clusters w/version 1.8.0-rc1
          - clusters:
              selector:
                matchExpressions:
                  - key: kyverno
                    operator: In
                    values:
                      - dev
                  - key: clusterName
                    operator: In
                    values:
                      - c-build-2
              values:
                path: kyverno/1.8.0-rc1
  template:
    metadata:
      name: 'kyverno-me-{{name}}'
      labels:
        appset: kyverno-merge
        clusterId: '{{metadata.labels.clusterId}}'
        environmentId: '{{metadata.labels.environmentId}}'
      annotations:
        argocd.argoproj.io/sync-wave: "3001"
        version: '{{values.path}}'
    spec:
      project: kyverno
      source:
        helm:
          valueFiles:
          - '{{values.valueFile}}'
        repoURL: 'https://github.com/ron1/ron1-kyverno-gitops.git'
        targetRevision: HEAD
        path: '{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: kyverno
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
          # - Replace=true # Set to workaround CRD annotation length issue until Server-side apply is available in Argo 2.5
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
