apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3003"
  name: kyverno-policies
spec:
  generators:
    - merge:
        mergeKeys:
          - name
        generators:
          - clusters:
              selector:
                matchLabels:
                  clusterId: in-cluster-local
              values:
                path: kyverno-policies/1.7.1/overlays/clusters/in-cluster-local
          - clusters:
              selector:
                matchLabels:
                  clusterId: c-build-3
              values:
                path: kyverno-policies/1.7.1/base
  template:
    metadata:
      name: 'kyverno-policies-{{name}}'
      labels:
        appset: kyverno-policies
        clusterId: '{{metadata.labels.clusterId}}'
        environmentId: '{{metadata.labels.environmentId}}'
      annotations:
        argocd.argoproj.io/sync-wave: "3003"
        version: '{{values.path}}'
    spec:
      project: kyverno
      source:
        repoURL: 'https://github.com/ron1/ron1-kyverno-gitops.git'
        targetRevision: HEAD
        path: '{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: kyverno
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
